name = "aiworkers"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
# DEEPSEEK_API_KEY 在部署时通过 Cloudflare 仪表板设置
DEEPSEEK_API_KEY = ""
# 这里可以添加其他环境变量
# 添加允许的域名白名单，使用逗号分隔
ALLOWED_ORIGINS = "https://charadesgenerator.xyz,https://lettersamplegenerator.com"
